CREATE TABLE IF NOT EXISTS users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(56) NOT NULL,
    Password CHARACTER(20) NOT NULL,
    UNIQUE (Name) ON CONFLICT IGNORE,
    UNIQUE (Name, Password) ON CONFLICT IGNORE
);

CREATE TABLE IF NOT EXISTS deck (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID VARCHAR(56) NOT NULL,
    Name  VARCHAR(255) NOT NULL,
    FOREIGN KEY (UserID)
    REFERENCES users (ID) 
    ON DELETE CASCADE ON UPDATE NO ACTION
);
