CREATE TABLE IF NOT EXISTS users (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(56) NOT NULL,
    Password CHARACTER(20) NOT NULL,
    UNIQUE (Name) ON CONFLICT IGNORE,
    UNIQUE (Name, Password) ON CONFLICT IGNORE
);

